# Generated by Django 5.2.8 on 2026-05-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Optional Meta Description for SEO purposes', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Optional SEO Title to override the default title', max_length=255, null=True),
        ),
    ]
